[project]
name = "tomyou-ea"
version = "0.1.0"
description = "tomyou-ea"
authors = [
{ name = "tomyou" }
]
dependencies = [
"fastapi>=0.111.0",
"uvicorn>=0.30.1",
"sqlalchemy>=2.0.30",
"aiomysql>=0.2.0",
"injector>=0.21.0",
"python-dotenv>=1.0.1",
"python-multipart>=0.0.9",
"python-jose[cryptography]>=3.3.0",
"passlib[bcrypt]>=1.7.4",
"psycopg2-binary>=2.9.9",
"asyncpg>=0.29.0",
"pandas>=2.2.2",
]
readme = "README.md"
requires-python = ">= 3.11"

[tool.uv]
dev-dependencies = [
"mypy>=1.11.2",
"pytest>=8.3.2",
"ruff>=0.6.3",
"requests>=2.32.3",
"sqlacodegen>=3.0.0rc5",
]

[tool.setuptools]
py-modules = ["app_server"]
